# Generated by Django 4.2.6 on 2023-12-11 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bno', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
